// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Tea_app from "bucklescript-tea/src-ocaml/tea_app.js";
import * as Tea_cmd from "bucklescript-tea/src-ocaml/tea_cmd.js";
import * as Tea_sub from "bucklescript-tea/src-ocaml/tea_sub.js";
import * as Tea_html from "bucklescript-tea/src-ocaml/tea_html.js";

function init() {
  return /* tuple */[
          "abc",
          Tea_cmd.none
        ];
}

function update(model, _) {
  return /* tuple */[
          model,
          Tea_cmd.none
        ];
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.aside(undefined, undefined, /* [] */0, /* [] */0),
              /* :: */[
                Tea_html.main(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.text(model),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

function partial_arg_003() {
  return Tea_sub.none;
}

var partial_arg = /* record */[
  /* init */init,
  /* update */update,
  /* view */view,
  partial_arg_003
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

export {
  init ,
  update ,
  view ,
  main ,
  
}
/* Tea_html Not a pure module */
