// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Tea_html = require("bucklescript-tea/src-ocaml/tea_html.js");

function license() {
  return /* :: */[
          Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                Tea_html.text("The OCaml system is copyright &#XA9; 1996&#X2013;2013\r\n      Institut National de Recherche en Informatique et en\r\n      Automatique (INRIA).\r\n      INRIA holds all ownership rights to the OCaml system."),
                /* [] */0
              ]),
          /* :: */[
            Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                  Tea_html.text("The OCaml system is open source and can be freely\r\n      redistributed. See the file <span class=\"c003\">LICENSE</span> in the distribution for\r\n      licensing information."),
                  /* [] */0
                ]),
            /* :: */[
              Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("The present documentation is copyright &#XA9; 2013\r\n      Institut National de Recherche en Informatique et en\r\n      Automatique (INRIA). The OCaml documentation and user&#X2019;s\r\n      manual may be reproduced and distributed in whole or\r\n      in part, subject to the following conditions:"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.ul(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                            Tea_html.text(" The copyright notice above and this permission notice must be\r\n            preserved complete on all complete or partial copies."),
                            /* [] */0
                          ]),
                      /* :: */[
                        Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                              Tea_html.text("Any translation or derivative work of the OCaml\r\n            documentation and user&#X2019;s manual must be approved by the authors in\r\n            writing before distribution."),
                              /* [] */0
                            ]),
                        /* :: */[
                          Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                                Tea_html.text("If you distribute the OCaml\r\n            documentation and user&#X2019;s manual in part, instructions for obtaining\r\n            the complete version of this manual must be included, and a\r\n            means for obtaining a complete version provided."),
                                /* [] */0
                              ]),
                          /* :: */[
                            Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                                  Tea_html.text("Small portions may be reproduced as illustrations for reviews or\r\n            quotes in other works without this permission notice if proper\r\n            citation is given."),
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ];
}

exports.license = license;
/* Tea_html Not a pure module */
