// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Types = require("./types.bs.js");
var Tea_html = require("bucklescript-tea/src-ocaml/tea_html.js");
var Tea_json = require("bucklescript-tea/src-ocaml/tea_json.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

function onEnter(msg) {
  var isEnter = function (code) {
    if (code === 13) {
      return Tea_json.Decoder[/* succeed */24](msg);
    } else {
      return Tea_json.Decoder[/* fail */25]("not ENTER");
    }
  };
  return Tea_html.on("keydown", Tea_json.Decoder[/* andThen */27](isEnter, Tea_html.keyCode));
}

function function_links(sidebar_link) {
  return List.map((function (func_name) {
                return Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                            Tea_html.a(undefined, undefined, /* :: */[
                                  Tea_html.href("#" + (sidebar_link[/* name */0] + ("-" + func_name))),
                                  /* [] */0
                                ], /* :: */[
                                  Tea_html.text(func_name),
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]);
              }), sidebar_link[/* functions */2]);
}

function sidebar_functions(sidebar_link) {
  return Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.onClick(/* ClickedSidebarLink */Block.__(1, [
                            sidebar_link[/* name */0],
                            true
                          ])),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text("Functions"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.ul(undefined, undefined, /* :: */[
                      Tea_html.classList(/* :: */[
                            /* tuple */[
                              "function-links",
                              true
                            ],
                            /* :: */[
                              /* tuple */[
                                "selected",
                                sidebar_link[/* functions_selected */3]
                              ],
                              /* [] */0
                            ]
                          ]),
                      /* [] */0
                    ], function_links(sidebar_link)),
                /* [] */0
              ]
            ]);
}

function sublist_sidebar(sidebar_link) {
  var add_sidebar_functions = function (list) {
    if (List.length(sidebar_link[/* functions */2]) > 0) {
      return /* :: */[
              sidebar_functions(sidebar_link),
              list
            ];
    } else {
      return list;
    }
  };
  return Tea_html.ul(undefined, undefined, /* :: */[
              Tea_html.classList(/* :: */[
                    /* tuple */[
                      "sublist",
                      true
                    ],
                    /* :: */[
                      /* tuple */[
                        "selected",
                        sidebar_link[/* selected */1]
                      ],
                      /* [] */0
                    ]
                  ]),
              /* [] */0
            ], /* :: */[
              Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.a(undefined, undefined, /* :: */[
                          Tea_html.href("#" + sidebar_link[/* name */0]),
                          /* [] */0
                        ], /* :: */[
                          Tea_html.text("Top"),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]),
              add_sidebar_functions(/* [] */0)
            ]);
}

function sidebar_link(sidebar_link$1) {
  return Tea_html.li(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.onClick(/* ClickedSidebarLink */Block.__(1, [
                            sidebar_link$1[/* name */0],
                            false
                          ])),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.text(sidebar_link$1[/* name */0]),
                    /* [] */0
                  ]),
              /* :: */[
                sublist_sidebar(sidebar_link$1),
                /* [] */0
              ]
            ]);
}

function module_sidebar_links(sidebar_links) {
  return List.map(sidebar_link, sidebar_links);
}

function sidebar_element_results(search_results) {
  return List.map((function (param) {
                return Tea_html.ul(undefined, undefined, /* :: */[
                            Tea_html.class$prime("search-result-category-list"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.h5(undefined, undefined, /* :: */[
                                  Tea_html.class$prime("search-result-category"),
                                  /* [] */0
                                ], /* :: */[
                                  Tea_html.text(param[0]),
                                  /* [] */0
                                ]),
                            /* :: */[
                              Tea_html.ul(undefined, undefined, /* :: */[
                                    Tea_html.class$prime("search-result-elements-list"),
                                    /* [] */0
                                  ], List.map((function (name) {
                                          return Tea_html.li(undefined, undefined, /* :: */[
                                                      Tea_html.class$prime("search-result-element"),
                                                      /* [] */0
                                                    ], /* :: */[
                                                      Tea_html.a(undefined, undefined, /* :: */[
                                                            Tea_html.href("#" + (search_results[/* module_group */0] + ("-" + name))),
                                                            /* [] */0
                                                          ], /* :: */[
                                                            Tea_html.text(name),
                                                            /* [] */0
                                                          ]),
                                                      /* [] */0
                                                    ]);
                                        }), param[1])),
                              /* [] */0
                            ]
                          ]);
              }), List.rev(Belt_MapString.toList(search_results[/* element_results */1])));
}

function sidebar_search_results_list(search_results) {
  return List.map((function (sr) {
                return Tea_html.ul(undefined, undefined, /* :: */[
                            Tea_html.class$prime("search-result-module-list"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.a(undefined, undefined, /* :: */[
                                  Tea_html.href("#" + sr[/* module_group */0]),
                                  /* [] */0
                                ], /* :: */[
                                  Tea_html.text(sr[/* module_group */0]),
                                  /* [] */0
                                ]),
                            sidebar_element_results(sr)
                          ]);
              }), search_results);
}

function sidebar_search_results(search_results) {
  return Pervasives.$at(/* :: */[
              Tea_html.div(undefined, undefined, /* :: */[
                    Tea_html.id("search-results-header"),
                    /* [] */0
                  ], /* :: */[
                    Tea_html.h3(undefined, undefined, /* :: */[
                          Tea_html.id("search-results-title"),
                          /* [] */0
                        ], /* :: */[
                          Tea_html.text("Results"),
                          /* [] */0
                        ]),
                    /* :: */[
                      Tea_html.button(undefined, undefined, /* :: */[
                            Tea_html.id("clear-button"),
                            /* :: */[
                              Tea_html.onClick(/* Clear */2),
                              /* [] */0
                            ]
                          ], /* :: */[
                            Tea_html.text("Clear"),
                            /* [] */0
                          ]),
                      /* [] */0
                    ]
                  ]),
              /* [] */0
            ], sidebar_search_results_list(search_results));
}

function sidebar_content(sidebar) {
  return /* :: */[
          Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.id("search-results"),
                /* :: */[
                  Tea_html.classList(/* :: */[
                        /* tuple */[
                          "show-results",
                          List.length(sidebar[/* search_results */1]) > 0
                        ],
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ], sidebar_search_results(sidebar[/* search_results */1])),
          /* :: */[
            Tea_html.h3(undefined, undefined, /* :: */[
                  Tea_html.id("modules-title"),
                  /* [] */0
                ], /* :: */[
                  Tea_html.text("Modules"),
                  /* [] */0
                ]),
            /* :: */[
              Tea_html.ul(undefined, undefined, /* :: */[
                    Tea_html.class$prime("module-links"),
                    /* [] */0
                  ], List.map(sidebar_link, sidebar[/* sidebar_links */2])),
              /* [] */0
            ]
          ]
        ];
}

function sidebar_header(sidebar) {
  return /* :: */[
          Tea_html.a(undefined, undefined, /* :: */[
                Tea_html.href("#docs_home"),
                /* [] */0
              ], /* :: */[
                Tea_html.img(undefined, undefined, /* :: */[
                      Tea_html.src("http://ocaml.org/img/colour-logo-white.svg"),
                      /* :: */[
                        Tea_html.id("logo"),
                        /* [] */0
                      ]
                    ], /* [] */0),
                /* [] */0
              ]),
          /* :: */[
            Tea_html.h5(undefined, undefined, /* :: */[
                  Tea_html.id("version"),
                  /* [] */0
                ], /* :: */[
                  Tea_html.text("v4.07 (Unofficial)"),
                  /* [] */0
                ]),
            /* :: */[
              Tea_html.h6(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.a(undefined, undefined, /* :: */[
                          Tea_html.href("https://caml.inria.fr/pub/docs/manual-ocaml-4.07/"),
                          /* [] */0
                        ], /* :: */[
                          Tea_html.text("Official Docs"),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.h6(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.a(undefined, undefined, /* :: */[
                            Tea_html.href("https://ocaml.org/"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.text("Official Website"),
                            /* [] */0
                          ]),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.h6(undefined, undefined, /* :: */[
                        Tea_html.id("back-link"),
                        /* [] */0
                      ], /* :: */[
                        Tea_html.a(undefined, undefined, /* :: */[
                              Tea_html.href("https://www.streamingspring.com"),
                              /* [] */0
                            ], /* :: */[
                              Tea_html.text("<- Back to Blog"),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]),
                  /* :: */[
                    Tea_html.input$prime(undefined, undefined, /* :: */[
                          Tea_html.type$prime("text"),
                          /* :: */[
                            Tea_html.id("search-bar"),
                            /* :: */[
                              Tea_html.value(sidebar[/* search_term */0]),
                              /* :: */[
                                Tea_html.onInput(undefined, Types.updateSearchTerm),
                                /* :: */[
                                  onEnter(/* Search */1),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ], /* [] */0),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ];
}

function view_sidebar(sidebar) {
  return Tea_html.aside(undefined, undefined, /* :: */[
              Tea_html.classList(/* :: */[
                    /* tuple */[
                      "sidebar",
                      true
                    ],
                    /* :: */[
                      /* tuple */[
                        "selected",
                        sidebar[/* icon_selected */3]
                      ],
                      /* [] */0
                    ]
                  ]),
              /* [] */0
            ], /* :: */[
              Tea_html.div(undefined, undefined, /* :: */[
                    Tea_html.id("sidebar-header"),
                    /* [] */0
                  ], sidebar_header(sidebar)),
              /* :: */[
                Tea_html.div(undefined, undefined, /* :: */[
                      Tea_html.id("sidebar-content"),
                      /* [] */0
                    ], sidebar_content(sidebar)),
                /* [] */0
              ]
            ]);
}

exports.onEnter = onEnter;
exports.function_links = function_links;
exports.sidebar_functions = sidebar_functions;
exports.sublist_sidebar = sublist_sidebar;
exports.sidebar_link = sidebar_link;
exports.module_sidebar_links = module_sidebar_links;
exports.sidebar_element_results = sidebar_element_results;
exports.sidebar_search_results_list = sidebar_search_results_list;
exports.sidebar_search_results = sidebar_search_results;
exports.sidebar_content = sidebar_content;
exports.sidebar_header = sidebar_header;
exports.view_sidebar = view_sidebar;
/* Tea_html Not a pure module */
