// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function urlChange(param_0) {
  return /* UrlChange */Block.__(0, [param_0]);
}

function clickedSidebarLink(param_0, param_1) {
  return /* ClickedSidebarLink */Block.__(1, [
            param_0,
            param_1
          ]);
}

function updateSearchTerm(param_0) {
  return /* UpdateSearchTerm */Block.__(2, [param_0]);
}

var scroll = /* Scroll */0;

var search = /* Search */1;

var clear = /* Clear */2;

var clickedSidebarIcon = /* ClickedSidebarIcon */3;

var toggleModuleSwitch = /* ToggleModuleSwitch */4;

exports.urlChange = urlChange;
exports.clickedSidebarLink = clickedSidebarLink;
exports.scroll = scroll;
exports.updateSearchTerm = updateSearchTerm;
exports.search = search;
exports.clear = clear;
exports.clickedSidebarIcon = clickedSidebarIcon;
exports.toggleModuleSwitch = toggleModuleSwitch;
/* No side effect */
